

import sys
from PyQt6 import uic
from PyQt6.QtWidgets import QApplication, QMainWindow, QWidget
from PyQt6.QtCore import Qt
import ctypes

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1482, 1062)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 170, 1161, 461))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(40, 110, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 140, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(40, 170, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setGeometry(QtCore.QRect(40, 200, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.frame)
        self.label_5.setGeometry(QtCore.QRect(130, 80, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_15 = QtWidgets.QLabel(parent=self.frame)
        self.label_15.setGeometry(QtCore.QRect(940, 40, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(110, 110, 61, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 140, 61, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(110, 170, 61, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(110, 200, 61, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_5.setGeometry(QtCore.QRect(180, 170, 61, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_6.setGeometry(QtCore.QRect(180, 140, 61, 21))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_7.setGeometry(QtCore.QRect(180, 110, 61, 21))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_8.setGeometry(QtCore.QRect(180, 200, 61, 21))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_9.setGeometry(QtCore.QRect(250, 170, 61, 21))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_10.setGeometry(QtCore.QRect(250, 140, 61, 21))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_11.setGeometry(QtCore.QRect(250, 110, 61, 21))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_12.setGeometry(QtCore.QRect(250, 200, 61, 21))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_13.setGeometry(QtCore.QRect(330, 170, 61, 21))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_14.setGeometry(QtCore.QRect(330, 140, 61, 21))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_15.setGeometry(QtCore.QRect(330, 110, 61, 21))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_16.setGeometry(QtCore.QRect(330, 200, 61, 21))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_17.setGeometry(QtCore.QRect(400, 170, 61, 21))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_18.setGeometry(QtCore.QRect(400, 140, 61, 21))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_19.setGeometry(QtCore.QRect(400, 110, 61, 21))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_20.setGeometry(QtCore.QRect(400, 200, 61, 21))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_40 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_40.setGeometry(QtCore.QRect(760, 200, 61, 21))
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.lineEdit_22 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_22.setGeometry(QtCore.QRect(470, 170, 61, 21))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_35 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_35.setGeometry(QtCore.QRect(540, 200, 61, 21))
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.lineEdit_25 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_25.setGeometry(QtCore.QRect(760, 110, 61, 21))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.lineEdit_32 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_32.setGeometry(QtCore.QRect(610, 110, 61, 21))
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.lineEdit_26 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_26.setGeometry(QtCore.QRect(690, 110, 61, 21))
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.lineEdit_33 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_33.setGeometry(QtCore.QRect(470, 110, 61, 21))
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.lineEdit_24 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_24.setGeometry(QtCore.QRect(690, 140, 61, 21))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.lineEdit_28 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_28.setGeometry(QtCore.QRect(540, 170, 61, 21))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.lineEdit_36 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_36.setGeometry(QtCore.QRect(540, 140, 61, 21))
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.lineEdit_31 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_31.setGeometry(QtCore.QRect(610, 170, 61, 21))
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.lineEdit_30 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_30.setGeometry(QtCore.QRect(610, 140, 61, 21))
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.lineEdit_23 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_23.setGeometry(QtCore.QRect(610, 200, 61, 21))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.lineEdit_37 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_37.setGeometry(QtCore.QRect(690, 200, 61, 21))
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.lineEdit_29 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_29.setGeometry(QtCore.QRect(470, 140, 61, 21))
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.lineEdit_27 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_27.setGeometry(QtCore.QRect(690, 170, 61, 21))
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.lineEdit_38 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_38.setGeometry(QtCore.QRect(760, 170, 61, 21))
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.lineEdit_39 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_39.setGeometry(QtCore.QRect(760, 140, 61, 21))
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.lineEdit_21 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_21.setGeometry(QtCore.QRect(540, 110, 61, 21))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_34 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_34.setGeometry(QtCore.QRect(470, 200, 61, 21))
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.lineEdit_41 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_41.setGeometry(QtCore.QRect(900, 110, 61, 21))
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.lineEdit_43 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_43.setGeometry(QtCore.QRect(970, 200, 61, 21))
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.lineEdit_50 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_50.setGeometry(QtCore.QRect(970, 140, 61, 21))
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.lineEdit_51 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_51.setGeometry(QtCore.QRect(970, 170, 61, 21))
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.lineEdit_54 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_54.setGeometry(QtCore.QRect(830, 200, 61, 21))
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.lineEdit_42 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_42.setGeometry(QtCore.QRect(830, 170, 61, 21))
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.lineEdit_55 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_55.setGeometry(QtCore.QRect(900, 200, 61, 21))
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.lineEdit_56 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_56.setGeometry(QtCore.QRect(900, 140, 61, 21))
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.lineEdit_48 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_48.setGeometry(QtCore.QRect(900, 170, 61, 21))
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.lineEdit_53 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_53.setGeometry(QtCore.QRect(830, 110, 61, 21))
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.lineEdit_52 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_52.setGeometry(QtCore.QRect(970, 110, 61, 21))
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.lineEdit_49 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_49.setGeometry(QtCore.QRect(830, 140, 61, 21))
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.label_6 = QtWidgets.QLabel(parent=self.frame)
        self.label_6.setGeometry(QtCore.QRect(200, 80, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.frame)
        self.label_7.setGeometry(QtCore.QRect(270, 80, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.frame)
        self.label_8.setGeometry(QtCore.QRect(350, 80, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.frame)
        self.label_9.setGeometry(QtCore.QRect(420, 80, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.frame)
        self.label_10.setGeometry(QtCore.QRect(500, 80, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.frame)
        self.label_11.setGeometry(QtCore.QRect(560, 80, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.frame)
        self.label_12.setGeometry(QtCore.QRect(630, 80, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(parent=self.frame)
        self.label_13.setGeometry(QtCore.QRect(710, 80, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(parent=self.frame)
        self.label_14.setGeometry(QtCore.QRect(770, 80, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_16 = QtWidgets.QLabel(parent=self.frame)
        self.label_16.setGeometry(QtCore.QRect(840, 80, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(parent=self.frame)
        self.label_17.setGeometry(QtCore.QRect(920, 80, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(parent=self.frame)
        self.label_18.setGeometry(QtCore.QRect(980, 80, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_36 = QtWidgets.QLabel(parent=self.frame)
        self.label_36.setGeometry(QtCore.QRect(560, 40, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.lineEdit_47 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_47.setGeometry(QtCore.QRect(110, 390, 61, 21))
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.lineEdit_77 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_77.setGeometry(QtCore.QRect(470, 420, 61, 21))
        self.lineEdit_77.setObjectName("lineEdit_77")
        self.lineEdit_98 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_98.setGeometry(QtCore.QRect(980, 390, 61, 21))
        self.lineEdit_98.setObjectName("lineEdit_98")
        self.lineEdit_81 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_81.setGeometry(QtCore.QRect(840, 360, 61, 21))
        self.lineEdit_81.setObjectName("lineEdit_81")
        self.lineEdit_100 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_100.setGeometry(QtCore.QRect(840, 330, 61, 21))
        self.lineEdit_100.setObjectName("lineEdit_100")
        self.lineEdit_62 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_62.setGeometry(QtCore.QRect(250, 390, 61, 21))
        self.lineEdit_62.setObjectName("lineEdit_62")
        self.lineEdit_82 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_82.setGeometry(QtCore.QRect(980, 330, 61, 21))
        self.lineEdit_82.setObjectName("lineEdit_82")
        self.lineEdit_73 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_73.setGeometry(QtCore.QRect(250, 330, 61, 21))
        self.lineEdit_73.setObjectName("lineEdit_73")
        self.lineEdit_89 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_89.setGeometry(QtCore.QRect(840, 420, 61, 21))
        self.lineEdit_89.setObjectName("lineEdit_89")
        self.lineEdit_67 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_67.setGeometry(QtCore.QRect(470, 390, 61, 21))
        self.lineEdit_67.setObjectName("lineEdit_67")
        self.label_29 = QtWidgets.QLabel(parent=self.frame)
        self.label_29.setGeometry(QtCore.QRect(240, 300, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_33 = QtWidgets.QLabel(parent=self.frame)
        self.label_33.setGeometry(QtCore.QRect(930, 300, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.lineEdit_64 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_64.setGeometry(QtCore.QRect(470, 360, 61, 21))
        self.lineEdit_64.setObjectName("lineEdit_64")
        self.lineEdit_58 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_58.setGeometry(QtCore.QRect(180, 390, 61, 21))
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.lineEdit_90 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_90.setGeometry(QtCore.QRect(690, 330, 61, 21))
        self.lineEdit_90.setObjectName("lineEdit_90")
        self.label_28 = QtWidgets.QLabel(parent=self.frame)
        self.label_28.setGeometry(QtCore.QRect(190, 300, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_34 = QtWidgets.QLabel(parent=self.frame)
        self.label_34.setGeometry(QtCore.QRect(990, 300, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_30 = QtWidgets.QLabel(parent=self.frame)
        self.label_30.setGeometry(QtCore.QRect(400, 300, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.lineEdit_72 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_72.setGeometry(QtCore.QRect(390, 330, 61, 21))
        self.lineEdit_72.setObjectName("lineEdit_72")
        self.lineEdit_78 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_78.setGeometry(QtCore.QRect(540, 390, 61, 21))
        self.lineEdit_78.setObjectName("lineEdit_78")
        self.lineEdit_94 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_94.setGeometry(QtCore.QRect(980, 360, 61, 21))
        self.lineEdit_94.setObjectName("lineEdit_94")
        self.lineEdit_86 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_86.setGeometry(QtCore.QRect(770, 330, 61, 21))
        self.lineEdit_86.setObjectName("lineEdit_86")
        self.lineEdit_63 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_63.setGeometry(QtCore.QRect(390, 420, 61, 21))
        self.lineEdit_63.setObjectName("lineEdit_63")
        self.label_22 = QtWidgets.QLabel(parent=self.frame)
        self.label_22.setGeometry(QtCore.QRect(630, 300, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_25 = QtWidgets.QLabel(parent=self.frame)
        self.label_25.setGeometry(QtCore.QRect(550, 300, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.lineEdit_103 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_103.setGeometry(QtCore.QRect(910, 330, 61, 21))
        self.lineEdit_103.setObjectName("lineEdit_103")
        self.lineEdit_71 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_71.setGeometry(QtCore.QRect(390, 390, 61, 21))
        self.lineEdit_71.setObjectName("lineEdit_71")
        self.lineEdit_76 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_76.setGeometry(QtCore.QRect(320, 360, 61, 21))
        self.lineEdit_76.setObjectName("lineEdit_76")
        self.lineEdit_95 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_95.setGeometry(QtCore.QRect(840, 390, 61, 21))
        self.lineEdit_95.setObjectName("lineEdit_95")
        self.lineEdit_99 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_99.setGeometry(QtCore.QRect(690, 360, 61, 21))
        self.lineEdit_99.setObjectName("lineEdit_99")
        self.label_32 = QtWidgets.QLabel(parent=self.frame)
        self.label_32.setGeometry(QtCore.QRect(850, 300, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.lineEdit_75 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_75.setGeometry(QtCore.QRect(320, 420, 61, 21))
        self.lineEdit_75.setObjectName("lineEdit_75")
        self.lineEdit_60 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_60.setGeometry(QtCore.QRect(180, 420, 61, 21))
        self.lineEdit_60.setObjectName("lineEdit_60")
        self.lineEdit_104 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_104.setGeometry(QtCore.QRect(910, 390, 61, 21))
        self.lineEdit_104.setObjectName("lineEdit_104")
        self.label_24 = QtWidgets.QLabel(parent=self.frame)
        self.label_24.setGeometry(QtCore.QRect(770, 300, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.lineEdit_65 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_65.setGeometry(QtCore.QRect(540, 330, 61, 21))
        self.lineEdit_65.setObjectName("lineEdit_65")
        self.lineEdit_61 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_61.setGeometry(QtCore.QRect(320, 330, 61, 21))
        self.lineEdit_61.setObjectName("lineEdit_61")
        self.lineEdit_59 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_59.setGeometry(QtCore.QRect(180, 360, 61, 21))
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.lineEdit_92 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_92.setGeometry(QtCore.QRect(690, 390, 61, 21))
        self.lineEdit_92.setObjectName("lineEdit_92")
        self.lineEdit_68 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_68.setGeometry(QtCore.QRect(320, 390, 61, 21))
        self.lineEdit_68.setObjectName("lineEdit_68")
        self.label_23 = QtWidgets.QLabel(parent=self.frame)
        self.label_23.setGeometry(QtCore.QRect(700, 300, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.lineEdit_46 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_46.setGeometry(QtCore.QRect(110, 330, 61, 21))
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.lineEdit_74 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_74.setGeometry(QtCore.QRect(250, 420, 61, 21))
        self.lineEdit_74.setObjectName("lineEdit_74")
        self.lineEdit_85 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_85.setGeometry(QtCore.QRect(770, 420, 61, 21))
        self.lineEdit_85.setObjectName("lineEdit_85")
        self.label_20 = QtWidgets.QLabel(parent=self.frame)
        self.label_20.setGeometry(QtCore.QRect(350, 260, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(parent=self.frame)
        self.label_21.setGeometry(QtCore.QRect(500, 260, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.lineEdit_84 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_84.setGeometry(QtCore.QRect(690, 420, 61, 21))
        self.lineEdit_84.setObjectName("lineEdit_84")
        self.label_19 = QtWidgets.QLabel(parent=self.frame)
        self.label_19.setGeometry(QtCore.QRect(160, 260, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.lineEdit_80 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_80.setGeometry(QtCore.QRect(540, 420, 61, 21))
        self.lineEdit_80.setObjectName("lineEdit_80")
        self.lineEdit_97 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_97.setGeometry(QtCore.QRect(770, 390, 61, 21))
        self.lineEdit_97.setObjectName("lineEdit_97")
        self.lineEdit_83 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_83.setGeometry(QtCore.QRect(620, 390, 61, 21))
        self.lineEdit_83.setObjectName("lineEdit_83")
        self.lineEdit_69 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_69.setGeometry(QtCore.QRect(250, 360, 61, 21))
        self.lineEdit_69.setObjectName("lineEdit_69")
        self.lineEdit_96 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_96.setGeometry(QtCore.QRect(620, 360, 61, 21))
        self.lineEdit_96.setObjectName("lineEdit_96")
        self.lineEdit_93 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_93.setGeometry(QtCore.QRect(620, 330, 61, 21))
        self.lineEdit_93.setObjectName("lineEdit_93")
        self.lineEdit_45 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_45.setGeometry(QtCore.QRect(180, 330, 61, 21))
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.lineEdit_102 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_102.setGeometry(QtCore.QRect(910, 360, 61, 21))
        self.lineEdit_102.setObjectName("lineEdit_102")
        self.lineEdit_87 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_87.setGeometry(QtCore.QRect(620, 420, 61, 21))
        self.lineEdit_87.setObjectName("lineEdit_87")
        self.lineEdit_88 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_88.setGeometry(QtCore.QRect(980, 420, 61, 21))
        self.lineEdit_88.setObjectName("lineEdit_88")
        self.label_27 = QtWidgets.QLabel(parent=self.frame)
        self.label_27.setGeometry(QtCore.QRect(120, 300, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.lineEdit_79 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_79.setGeometry(QtCore.QRect(540, 360, 61, 21))
        self.lineEdit_79.setObjectName("lineEdit_79")
        self.lineEdit_44 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_44.setGeometry(QtCore.QRect(110, 360, 61, 21))
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.lineEdit_70 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_70.setGeometry(QtCore.QRect(390, 360, 61, 21))
        self.lineEdit_70.setObjectName("lineEdit_70")
        self.lineEdit_101 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_101.setGeometry(QtCore.QRect(910, 420, 61, 21))
        self.lineEdit_101.setObjectName("lineEdit_101")
        self.label_35 = QtWidgets.QLabel(parent=self.frame)
        self.label_35.setGeometry(QtCore.QRect(480, 300, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.lineEdit_66 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_66.setGeometry(QtCore.QRect(470, 330, 61, 21))
        self.lineEdit_66.setObjectName("lineEdit_66")
        self.lineEdit_57 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_57.setGeometry(QtCore.QRect(110, 420, 61, 21))
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.label_26 = QtWidgets.QLabel(parent=self.frame)
        self.label_26.setGeometry(QtCore.QRect(770, 260, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.lineEdit_91 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_91.setGeometry(QtCore.QRect(770, 360, 61, 21))
        self.lineEdit_91.setObjectName("lineEdit_91")
        self.label_31 = QtWidgets.QLabel(parent=self.frame)
        self.label_31.setGeometry(QtCore.QRect(330, 300, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_37 = QtWidgets.QLabel(parent=self.frame)
        self.label_37.setGeometry(QtCore.QRect(40, 330, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(parent=self.frame)
        self.label_38.setGeometry(QtCore.QRect(40, 360, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(parent=self.frame)
        self.label_39.setGeometry(QtCore.QRect(40, 390, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(parent=self.frame)
        self.label_40.setGeometry(QtCore.QRect(40, 420, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(parent=self.frame)
        self.label_41.setGeometry(QtCore.QRect(30, 20, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 630, 1161, 381))
        self.widget.setStyleSheet("background-color: rgb(239, 253, 255);")
        self.widget.setObjectName("widget")
        self.label_42 = QtWidgets.QLabel(parent=self.widget)
        self.label_42.setGeometry(QtCore.QRect(30, 10, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(parent=self.widget)
        self.label_43.setGeometry(QtCore.QRect(30, 60, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(parent=self.widget)
        self.label_44.setGeometry(QtCore.QRect(30, 90, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(parent=self.widget)
        self.label_45.setGeometry(QtCore.QRect(30, 120, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(parent=self.widget)
        self.label_46.setGeometry(QtCore.QRect(30, 150, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(parent=self.widget)
        self.label_47.setGeometry(QtCore.QRect(30, 180, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(parent=self.widget)
        self.label_48.setGeometry(QtCore.QRect(260, 20, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(parent=self.widget)
        self.label_49.setGeometry(QtCore.QRect(560, 20, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(parent=self.widget)
        self.label_50.setGeometry(QtCore.QRect(850, 20, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.lineEdit_105 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_105.setGeometry(QtCore.QRect(180, 60, 191, 21))
        self.lineEdit_105.setObjectName("lineEdit_105")
        self.lineEdit_106 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_106.setGeometry(QtCore.QRect(180, 90, 191, 21))
        self.lineEdit_106.setObjectName("lineEdit_106")
        self.lineEdit_107 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_107.setGeometry(QtCore.QRect(180, 120, 191, 21))
        self.lineEdit_107.setObjectName("lineEdit_107")
        self.lineEdit_108 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_108.setGeometry(QtCore.QRect(180, 150, 191, 21))
        self.lineEdit_108.setObjectName("lineEdit_108")
        self.lineEdit_109 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_109.setGeometry(QtCore.QRect(180, 180, 191, 21))
        self.lineEdit_109.setObjectName("lineEdit_109")
        self.lineEdit_119 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_119.setGeometry(QtCore.QRect(490, 150, 191, 21))
        self.lineEdit_119.setObjectName("lineEdit_119")
        self.lineEdit_116 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_116.setGeometry(QtCore.QRect(490, 60, 191, 21))
        self.lineEdit_116.setObjectName("lineEdit_116")
        self.lineEdit_115 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_115.setGeometry(QtCore.QRect(490, 180, 191, 21))
        self.lineEdit_115.setObjectName("lineEdit_115")
        self.lineEdit_117 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_117.setGeometry(QtCore.QRect(490, 120, 191, 21))
        self.lineEdit_117.setObjectName("lineEdit_117")
        self.lineEdit_118 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_118.setGeometry(QtCore.QRect(490, 90, 191, 21))
        self.lineEdit_118.setObjectName("lineEdit_118")
        self.lineEdit_120 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_120.setGeometry(QtCore.QRect(790, 180, 191, 21))
        self.lineEdit_120.setObjectName("lineEdit_120")
        self.lineEdit_121 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_121.setGeometry(QtCore.QRect(790, 60, 191, 21))
        self.lineEdit_121.setObjectName("lineEdit_121")
        self.lineEdit_122 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_122.setGeometry(QtCore.QRect(790, 120, 191, 21))
        self.lineEdit_122.setObjectName("lineEdit_122")
        self.lineEdit_123 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_123.setGeometry(QtCore.QRect(790, 90, 191, 21))
        self.lineEdit_123.setObjectName("lineEdit_123")
        self.lineEdit_124 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_124.setGeometry(QtCore.QRect(790, 150, 191, 21))
        self.lineEdit_124.setObjectName("lineEdit_124")
        self.lineEdit_129 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_129.setGeometry(QtCore.QRect(350, 260, 201, 21))
        self.lineEdit_129.setObjectName("lineEdit_129")
        self.lineEdit_126 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_126.setGeometry(QtCore.QRect(270, 260, 31, 21))
        self.lineEdit_126.setObjectName("lineEdit_126")
        self.label_59 = QtWidgets.QLabel(parent=self.widget)
        self.label_59.setGeometry(QtCore.QRect(30, 230, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.label_58 = QtWidgets.QLabel(parent=self.widget)
        self.label_58.setGeometry(QtCore.QRect(170, 260, 16, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.label_56 = QtWidgets.QLabel(parent=self.widget)
        self.label_56.setGeometry(QtCore.QRect(190, 230, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.lineEdit_127 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_127.setGeometry(QtCore.QRect(190, 260, 51, 21))
        self.lineEdit_127.setObjectName("lineEdit_127")
        self.label_60 = QtWidgets.QLabel(parent=self.widget)
        self.label_60.setGeometry(QtCore.QRect(310, 264, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.lineEdit_112 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_112.setGeometry(QtCore.QRect(110, 260, 51, 21))
        self.lineEdit_112.setObjectName("lineEdit_112")
        self.lineEdit_128 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_128.setGeometry(QtCore.QRect(10, 260, 81, 21))
        self.lineEdit_128.setObjectName("lineEdit_128")
        self.label_57 = QtWidgets.QLabel(parent=self.widget)
        self.label_57.setGeometry(QtCore.QRect(420, 230, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.lineEdit_139 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_139.setGeometry(QtCore.QRect(350, 290, 201, 21))
        self.lineEdit_139.setObjectName("lineEdit_139")
        self.label_63 = QtWidgets.QLabel(parent=self.widget)
        self.label_63.setGeometry(QtCore.QRect(170, 290, 16, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(parent=self.widget)
        self.label_64.setGeometry(QtCore.QRect(310, 295, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")
        self.lineEdit_136 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_136.setGeometry(QtCore.QRect(190, 290, 51, 21))
        self.lineEdit_136.setObjectName("lineEdit_136")
        self.lineEdit_135 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_135.setGeometry(QtCore.QRect(270, 290, 31, 21))
        self.lineEdit_135.setObjectName("lineEdit_135")
        self.lineEdit_137 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_137.setGeometry(QtCore.QRect(110, 290, 51, 21))
        self.lineEdit_137.setObjectName("lineEdit_137")
        self.lineEdit_138 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_138.setGeometry(QtCore.QRect(10, 290, 81, 21))
        self.lineEdit_138.setObjectName("lineEdit_138")
        self.lineEdit_144 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_144.setGeometry(QtCore.QRect(350, 320, 201, 21))
        self.lineEdit_144.setObjectName("lineEdit_144")
        self.label_66 = QtWidgets.QLabel(parent=self.widget)
        self.label_66.setGeometry(QtCore.QRect(310, 324, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_66.setFont(font)
        self.label_66.setObjectName("label_66")
        self.lineEdit_143 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_143.setGeometry(QtCore.QRect(10, 320, 81, 21))
        self.lineEdit_143.setObjectName("lineEdit_143")
        self.lineEdit_140 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_140.setGeometry(QtCore.QRect(270, 320, 31, 21))
        self.lineEdit_140.setObjectName("lineEdit_140")
        self.lineEdit_142 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_142.setGeometry(QtCore.QRect(110, 320, 51, 21))
        self.lineEdit_142.setObjectName("lineEdit_142")
        self.label_65 = QtWidgets.QLabel(parent=self.widget)
        self.label_65.setGeometry(QtCore.QRect(170, 320, 16, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_65.setFont(font)
        self.label_65.setObjectName("label_65")
        self.lineEdit_141 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_141.setGeometry(QtCore.QRect(190, 320, 51, 21))
        self.lineEdit_141.setObjectName("lineEdit_141")
        self.lineEdit_149 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_149.setGeometry(QtCore.QRect(350, 350, 201, 21))
        self.lineEdit_149.setObjectName("lineEdit_149")
        self.label_67 = QtWidgets.QLabel(parent=self.widget)
        self.label_67.setGeometry(QtCore.QRect(170, 350, 16, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_67.setFont(font)
        self.label_67.setObjectName("label_67")
        self.lineEdit_148 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_148.setGeometry(QtCore.QRect(10, 350, 81, 21))
        self.lineEdit_148.setObjectName("lineEdit_148")
        self.lineEdit_147 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_147.setGeometry(QtCore.QRect(110, 350, 51, 21))
        self.lineEdit_147.setObjectName("lineEdit_147")
        self.label_68 = QtWidgets.QLabel(parent=self.widget)
        self.label_68.setGeometry(QtCore.QRect(310, 354, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_68.setFont(font)
        self.label_68.setObjectName("label_68")
        self.lineEdit_145 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_145.setGeometry(QtCore.QRect(270, 350, 31, 21))
        self.lineEdit_145.setObjectName("lineEdit_145")
        self.lineEdit_146 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_146.setGeometry(QtCore.QRect(190, 350, 51, 21))
        self.lineEdit_146.setObjectName("lineEdit_146")
        self.label_69 = QtWidgets.QLabel(parent=self.widget)
        self.label_69.setGeometry(QtCore.QRect(760, 350, 16, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_69.setFont(font)
        self.label_69.setObjectName("label_69")
        self.lineEdit_150 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_150.setGeometry(QtCore.QRect(860, 260, 31, 21))
        self.lineEdit_150.setObjectName("lineEdit_150")
        self.label_70 = QtWidgets.QLabel(parent=self.widget)
        self.label_70.setGeometry(QtCore.QRect(760, 290, 16, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_70.setFont(font)
        self.label_70.setObjectName("label_70")
        self.label_71 = QtWidgets.QLabel(parent=self.widget)
        self.label_71.setGeometry(QtCore.QRect(900, 324, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_71.setFont(font)
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QLabel(parent=self.widget)
        self.label_72.setGeometry(QtCore.QRect(900, 295, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_72.setFont(font)
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(parent=self.widget)
        self.label_73.setGeometry(QtCore.QRect(620, 230, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_73.setFont(font)
        self.label_73.setObjectName("label_73")
        self.lineEdit_151 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_151.setGeometry(QtCore.QRect(940, 320, 201, 21))
        self.lineEdit_151.setObjectName("lineEdit_151")
        self.label_74 = QtWidgets.QLabel(parent=self.widget)
        self.label_74.setGeometry(QtCore.QRect(760, 260, 16, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_74.setFont(font)
        self.label_74.setObjectName("label_74")
        self.lineEdit_152 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_152.setGeometry(QtCore.QRect(940, 350, 201, 21))
        self.lineEdit_152.setObjectName("lineEdit_152")
        self.label_75 = QtWidgets.QLabel(parent=self.widget)
        self.label_75.setGeometry(QtCore.QRect(780, 230, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_75.setFont(font)
        self.label_75.setObjectName("label_75")
        self.lineEdit_153 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_153.setGeometry(QtCore.QRect(600, 320, 81, 21))
        self.lineEdit_153.setObjectName("lineEdit_153")
        self.lineEdit_154 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_154.setGeometry(QtCore.QRect(780, 260, 51, 21))
        self.lineEdit_154.setObjectName("lineEdit_154")
        self.lineEdit_155 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_155.setGeometry(QtCore.QRect(860, 320, 31, 21))
        self.lineEdit_155.setObjectName("lineEdit_155")
        self.lineEdit_156 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_156.setGeometry(QtCore.QRect(600, 350, 81, 21))
        self.lineEdit_156.setObjectName("lineEdit_156")
        self.lineEdit_157 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_157.setGeometry(QtCore.QRect(700, 350, 51, 21))
        self.lineEdit_157.setObjectName("lineEdit_157")
        self.lineEdit_158 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_158.setGeometry(QtCore.QRect(700, 320, 51, 21))
        self.lineEdit_158.setObjectName("lineEdit_158")
        self.label_76 = QtWidgets.QLabel(parent=self.widget)
        self.label_76.setGeometry(QtCore.QRect(900, 264, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_76.setFont(font)
        self.label_76.setObjectName("label_76")
        self.lineEdit_159 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_159.setGeometry(QtCore.QRect(780, 290, 51, 21))
        self.lineEdit_159.setObjectName("lineEdit_159")
        self.lineEdit_160 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_160.setGeometry(QtCore.QRect(860, 290, 31, 21))
        self.lineEdit_160.setObjectName("lineEdit_160")
        self.lineEdit_161 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_161.setGeometry(QtCore.QRect(700, 290, 51, 21))
        self.lineEdit_161.setObjectName("lineEdit_161")
        self.label_77 = QtWidgets.QLabel(parent=self.widget)
        self.label_77.setGeometry(QtCore.QRect(900, 354, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_77.setFont(font)
        self.label_77.setObjectName("label_77")
        self.lineEdit_162 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_162.setGeometry(QtCore.QRect(700, 260, 51, 21))
        self.lineEdit_162.setObjectName("lineEdit_162")
        self.lineEdit_163 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_163.setGeometry(QtCore.QRect(600, 260, 81, 21))
        self.lineEdit_163.setObjectName("lineEdit_163")
        self.label_78 = QtWidgets.QLabel(parent=self.widget)
        self.label_78.setGeometry(QtCore.QRect(1010, 230, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_78.setFont(font)
        self.label_78.setObjectName("label_78")
        self.label_79 = QtWidgets.QLabel(parent=self.widget)
        self.label_79.setGeometry(QtCore.QRect(760, 320, 16, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_79.setFont(font)
        self.label_79.setObjectName("label_79")
        self.lineEdit_164 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_164.setGeometry(QtCore.QRect(940, 290, 201, 21))
        self.lineEdit_164.setObjectName("lineEdit_164")
        self.lineEdit_165 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_165.setGeometry(QtCore.QRect(600, 290, 81, 21))
        self.lineEdit_165.setObjectName("lineEdit_165")
        self.lineEdit_166 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_166.setGeometry(QtCore.QRect(780, 320, 51, 21))
        self.lineEdit_166.setObjectName("lineEdit_166")
        self.lineEdit_167 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_167.setGeometry(QtCore.QRect(860, 350, 31, 21))
        self.lineEdit_167.setObjectName("lineEdit_167")
        self.lineEdit_168 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_168.setGeometry(QtCore.QRect(780, 350, 51, 21))
        self.lineEdit_168.setObjectName("lineEdit_168")
        self.lineEdit_169 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_169.setGeometry(QtCore.QRect(940, 260, 201, 21))
        self.lineEdit_169.setObjectName("lineEdit_169")
        self.line = QtWidgets.QFrame(parent=self.widget)
        self.line.setGeometry(QtCore.QRect(10, 210, 1131, 21))

    # 여기에 변환된 UI 코드가 포함됩니다.
class MainWindow(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.resize(1920, 1080)
        self.setWindowState(Qt.WindowState.WindowMaximized)
        self.setWindowFlags(self.windowFlags() & ~Qt.WindowType.WindowMaximizeButtonHint)

if __name__ == "__main__":
    app = QApplication(sys.argv)
    myWindow = MainWindow()
    myWindow.show()
    sys.exit(app.exec())

